---
#
# Ansible managed
#
repository:
  description: Installs and configures Docker on Debian-based systems.
  homepage: https://mullholland.net
  topics: cloud, development, system, ansible, molecule, playbook
