---
- name: Install Docker.
  package:
    name: "{{ docker_packages }}"
    state: "{{ docker_package_state }}"

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true
