---
- name: Include distribution specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_facts["distribution"] }}-{{ ansible_facts["distribution_major_version"] }}.yml'
    - '{{ ansible_facts["distribution"] }}.yml'
    - '{{ ansible_facts["os_family"] }}.yml'
    - '{{ ansible_facts["system"] }}.yml'
    - 'default.yml'

- name: Prepare host
  ansible.builtin.include_tasks: prepare.yml

- name: Install Docker
  ansible.builtin.include_tasks: install.yml

- name: Configure Docker
  ansible.builtin.include_tasks: configure.yml
