---
- name: Ensure old versions of Docker are not installed.
  ansible.builtin.package:
    name: '{{ docker_packages_obsolete }}'
    state: absent

- name: Ensure depdencies are installed.
  ansible.builtin.package:
    name: "{{ docker_packages_dependencies }}"
    state: present

- name: prepare Debian specific
  include: prepare_Debian.yml
  when: ansible_os_family == "Debian"

- name: prepare RedHat specific
  include: prepare_RedHat.yml
  when: ansible_os_family == "RedHat"
