---
- name: prepare_debian | Add Docker apt key
  ansible.builtin.apt_key:
    url: "{{ docker_apt_repo_key_url }}"
    state: present

- name: prepare_debian | Add Docker apt repository
  ansible.builtin.template:
    src: "etc/apt/sources.list.d/docker.list.j2"
    dest: "/etc/apt/sources.list.d/docker.list"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: restart docker
  register: docker_repository_update

- name: prepare_debian | Update after Repository update
  ansible.builtin.apt:
    update_cache: true
  when: docker_repository_update.changed
  # E503 - Tasks that run when changed should likely be handlers
  # noe meta flush, we only want this
  tags:
    - skip_ansible_lint
